/* tslint:disable */
/* eslint-disable */
/**
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AnswerDto } from './answer-dto';
/**
 * 
 * @export
 * @interface AttemptDto
 */
export interface AttemptDto {
    /**
     * 
     * @type {number}
     * @memberof AttemptDto
     */
    testPassingId?: number;
    /**
     * 
     * @type {Date}
     * @memberof AttemptDto
     */
    finishedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof AttemptDto
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof AttemptDto
     */
    testId?: number;
    /**
     * 
     * @type {Array<AnswerDto>}
     * @memberof AttemptDto
     */
    answers?: Array<AnswerDto> | null;
}
