/* tslint:disable */
/* eslint-disable */
/**
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Gender } from './gender';
/**
 * 
 * @export
 * @interface DetailedUserInfoDto
 */
export interface DetailedUserInfoDto {
    /**
     * 
     * @type {number}
     * @memberof DetailedUserInfoDto
     */
    passedTestCount?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedUserInfoDto
     */
    createdTestCount?: number;
    /**
     * 
     * @type {Gender}
     * @memberof DetailedUserInfoDto
     */
    gender?: Gender;
    /**
     * 
     * @type {Date}
     * @memberof DetailedUserInfoDto
     */
    registrationDate?: Date;
}
