/* tslint:disable */
/* eslint-disable */
/**
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DetailedTestInfoDto
 */
export interface DetailedTestInfoDto {
    /**
     * 
     * @type {number}
     * @memberof DetailedTestInfoDto
     */
    averageTestCompletionTime?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedTestInfoDto
     */
    attemptCount?: number;
}
