/* tslint:disable */
/* eslint-disable */
/**
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewAnswerDto } from './new-answer-dto';
/**
 * 
 * @export
 * @interface NewAttemptDto
 */
export interface NewAttemptDto {
    /**
     * 
     * @type {number}
     * @memberof NewAttemptDto
     */
    testId?: number;
    /**
     * 
     * @type {Array<NewAnswerDto>}
     * @memberof NewAttemptDto
     */
    answers?: Array<NewAnswerDto> | null;
}
