/* tslint:disable */
/* eslint-disable */
/**
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QuestionType } from './question-type';
/**
 * 
 * @export
 * @interface NewAnswerDto
 */
export interface NewAnswerDto {
    /**
     * 
     * @type {number}
     * @memberof NewAnswerDto
     */
    questionNumber?: number;
    /**
     * 
     * @type {QuestionType}
     * @memberof NewAnswerDto
     */
    questionType?: QuestionType;
    /**
     * 
     * @type {string}
     * @memberof NewAnswerDto
     */
    answerText?: string | null;
}
