/* tslint:disable */
/* eslint-disable */
/**
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Question } from './question';
/**
 * 
 * @export
 * @interface TestDto
 */
export interface TestDto {
    /**
     * 
     * @type {number}
     * @memberof TestDto
     */
    testId?: number;
    /**
     * 
     * @type {string}
     * @memberof TestDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TestDto
     */
    ageRestriction?: number;
    /**
     * 
     * @type {number}
     * @memberof TestDto
     */
    questionCount?: number;
    /**
     * 
     * @type {string}
     * @memberof TestDto
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TestDto
     */
    creationDate?: Date;
    /**
     * 
     * @type {Array<Question>}
     * @memberof TestDto
     */
    questions?: Array<Question> | null;
}
