/* tslint:disable */
/* eslint-disable */
/**
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DetailedTestInfoDto } from './detailed-test-info-dto';
import { Question } from './question';
/**
 * 
 * @export
 * @interface TestFullInfoDto
 */
export interface TestFullInfoDto {
    /**
     * 
     * @type {number}
     * @memberof TestFullInfoDto
     */
    testId?: number;
    /**
     * 
     * @type {string}
     * @memberof TestFullInfoDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TestFullInfoDto
     */
    ageRestriction?: number;
    /**
     * 
     * @type {number}
     * @memberof TestFullInfoDto
     */
    questionCount?: number;
    /**
     * 
     * @type {string}
     * @memberof TestFullInfoDto
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TestFullInfoDto
     */
    creationDate?: Date;
    /**
     * 
     * @type {Array<Question>}
     * @memberof TestFullInfoDto
     */
    questions?: Array<Question> | null;
    /**
     * 
     * @type {DetailedTestInfoDto}
     * @memberof TestFullInfoDto
     */
    detailedTestInfo?: DetailedTestInfoDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof TestFullInfoDto
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof TestFullInfoDto
     */
    attemptIds?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof TestFullInfoDto
     */
    ownerId?: number;
}
