/* tslint:disable */
/* eslint-disable */
/**
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountMode } from './account-mode';
import { DetailedUserInfoDto } from './detailed-user-info-dto';
/**
 * 
 * @export
 * @interface UserFullInfoDto
 */
export interface UserFullInfoDto {
    /**
     * 
     * @type {number}
     * @memberof UserFullInfoDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof UserFullInfoDto
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserFullInfoDto
     */
    dateOfBirth?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserFullInfoDto
     */
    email?: string | null;
    /**
     * 
     * @type {AccountMode}
     * @memberof UserFullInfoDto
     */
    accountMode?: AccountMode;
    /**
     * 
     * @type {DetailedUserInfoDto}
     * @memberof UserFullInfoDto
     */
    detailedUserInfo?: DetailedUserInfoDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserFullInfoDto
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserFullInfoDto
     */
    testIds?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserFullInfoDto
     */
    attemptIds?: Array<number> | null;
}
