/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AnswerDto} from './AnswerDto';

/**
 * The AttemptDto model module.
 * @module model/AttemptDto
 * @version v1
 */
export class AttemptDto {
  /**
   * Constructs a new <code>AttemptDto</code>.
   * @alias module:model/AttemptDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AttemptDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AttemptDto} obj Optional instance to populate.
   * @return {module:model/AttemptDto} The populated <code>AttemptDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AttemptDto();
      if (data.hasOwnProperty('testPassingId'))
        obj.testPassingId = ApiClient.convertToType(data['testPassingId'], 'Number');
      if (data.hasOwnProperty('finishedAt'))
        obj.finishedAt = ApiClient.convertToType(data['finishedAt'], 'Date');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('testId'))
        obj.testId = ApiClient.convertToType(data['testId'], 'Number');
      if (data.hasOwnProperty('answers'))
        obj.answers = ApiClient.convertToType(data['answers'], [AnswerDto]);
    }
    return obj;
  }
}

/**
 * @member {Number} testPassingId
 */
AttemptDto.prototype.testPassingId = undefined;

/**
 * @member {Date} finishedAt
 */
AttemptDto.prototype.finishedAt = undefined;

/**
 * @member {Number} userId
 */
AttemptDto.prototype.userId = undefined;

/**
 * @member {Number} testId
 */
AttemptDto.prototype.testId = undefined;

/**
 * @member {Array.<module:model/AnswerDto>} answers
 */
AttemptDto.prototype.answers = undefined;

