/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Question} from './Question';

/**
 * The CreateTestDto model module.
 * @module model/CreateTestDto
 * @version v1
 */
export class CreateTestDto {
  /**
   * Constructs a new <code>CreateTestDto</code>.
   * @alias module:model/CreateTestDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateTestDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateTestDto} obj Optional instance to populate.
   * @return {module:model/CreateTestDto} The populated <code>CreateTestDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateTestDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('ageRestriction'))
        obj.ageRestriction = ApiClient.convertToType(data['ageRestriction'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('questions'))
        obj.questions = ApiClient.convertToType(data['questions'], [Question]);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
CreateTestDto.prototype.name = undefined;

/**
 * @member {Number} ageRestriction
 */
CreateTestDto.prototype.ageRestriction = undefined;

/**
 * @member {String} description
 */
CreateTestDto.prototype.description = undefined;

/**
 * @member {Array.<String>} tags
 */
CreateTestDto.prototype.tags = undefined;

/**
 * @member {Array.<module:model/Question>} questions
 */
CreateTestDto.prototype.questions = undefined;

