/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DetailedTestInfoDto model module.
 * @module model/DetailedTestInfoDto
 * @version v1
 */
export class DetailedTestInfoDto {
  /**
   * Constructs a new <code>DetailedTestInfoDto</code>.
   * @alias module:model/DetailedTestInfoDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DetailedTestInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DetailedTestInfoDto} obj Optional instance to populate.
   * @return {module:model/DetailedTestInfoDto} The populated <code>DetailedTestInfoDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DetailedTestInfoDto();
      if (data.hasOwnProperty('averageTestCompletionTime'))
        obj.averageTestCompletionTime = ApiClient.convertToType(data['averageTestCompletionTime'], 'Number');
      if (data.hasOwnProperty('attemptCount'))
        obj.attemptCount = ApiClient.convertToType(data['attemptCount'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} averageTestCompletionTime
 */
DetailedTestInfoDto.prototype.averageTestCompletionTime = undefined;

/**
 * @member {Number} attemptCount
 */
DetailedTestInfoDto.prototype.attemptCount = undefined;

