/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Gender} from './Gender';

/**
 * The DetailedUserInfoDto model module.
 * @module model/DetailedUserInfoDto
 * @version v1
 */
export class DetailedUserInfoDto {
  /**
   * Constructs a new <code>DetailedUserInfoDto</code>.
   * @alias module:model/DetailedUserInfoDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DetailedUserInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DetailedUserInfoDto} obj Optional instance to populate.
   * @return {module:model/DetailedUserInfoDto} The populated <code>DetailedUserInfoDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DetailedUserInfoDto();
      if (data.hasOwnProperty('passedTestCount'))
        obj.passedTestCount = ApiClient.convertToType(data['passedTestCount'], 'Number');
      if (data.hasOwnProperty('createdTestCount'))
        obj.createdTestCount = ApiClient.convertToType(data['createdTestCount'], 'Number');
      if (data.hasOwnProperty('gender'))
        obj.gender = Gender.constructFromObject(data['gender']);
      if (data.hasOwnProperty('registrationDate'))
        obj.registrationDate = ApiClient.convertToType(data['registrationDate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} passedTestCount
 */
DetailedUserInfoDto.prototype.passedTestCount = undefined;

/**
 * @member {Number} createdTestCount
 */
DetailedUserInfoDto.prototype.createdTestCount = undefined;

/**
 * @member {module:model/Gender} gender
 */
DetailedUserInfoDto.prototype.gender = undefined;

/**
 * @member {Date} registrationDate
 */
DetailedUserInfoDto.prototype.registrationDate = undefined;

