/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LoginDto model module.
 * @module model/LoginDto
 * @version v1
 */
export class LoginDto {
  /**
   * Constructs a new <code>LoginDto</code>.
   * @alias module:model/LoginDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LoginDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginDto} obj Optional instance to populate.
   * @return {module:model/LoginDto} The populated <code>LoginDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoginDto();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
LoginDto.prototype.email = undefined;

/**
 * @member {String} password
 */
LoginDto.prototype.password = undefined;

