/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {QuestionType} from './QuestionType';

/**
 * The NewAnswerDto model module.
 * @module model/NewAnswerDto
 * @version v1
 */
export class NewAnswerDto {
  /**
   * Constructs a new <code>NewAnswerDto</code>.
   * @alias module:model/NewAnswerDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NewAnswerDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewAnswerDto} obj Optional instance to populate.
   * @return {module:model/NewAnswerDto} The populated <code>NewAnswerDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NewAnswerDto();
      if (data.hasOwnProperty('questionNumber'))
        obj.questionNumber = ApiClient.convertToType(data['questionNumber'], 'Number');
      if (data.hasOwnProperty('questionType'))
        obj.questionType = QuestionType.constructFromObject(data['questionType']);
      if (data.hasOwnProperty('answerText'))
        obj.answerText = ApiClient.convertToType(data['answerText'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} questionNumber
 */
NewAnswerDto.prototype.questionNumber = undefined;

/**
 * @member {module:model/QuestionType} questionType
 */
NewAnswerDto.prototype.questionType = undefined;

/**
 * @member {String} answerText
 */
NewAnswerDto.prototype.answerText = undefined;

