/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {QuestionType} from './QuestionType';

/**
 * The Question model module.
 * @module model/Question
 * @version v1
 */
export class Question {
  /**
   * Constructs a new <code>Question</code>.
   * @alias module:model/Question
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Question</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Question} obj Optional instance to populate.
   * @return {module:model/Question} The populated <code>Question</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Question();
      if (data.hasOwnProperty('questionType'))
        obj.questionType = QuestionType.constructFromObject(data['questionType']);
      if (data.hasOwnProperty('choices'))
        obj.choices = ApiClient.convertToType(data['choices'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {module:model/QuestionType} questionType
 */
Question.prototype.questionType = undefined;

/**
 * @member {Array.<String>} choices
 */
Question.prototype.choices = undefined;

