/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AccountMode} from './AccountMode';

/**
 * The RegisterUserDto model module.
 * @module model/RegisterUserDto
 * @version v1
 */
export class RegisterUserDto {
  /**
   * Constructs a new <code>RegisterUserDto</code>.
   * @alias module:model/RegisterUserDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RegisterUserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisterUserDto} obj Optional instance to populate.
   * @return {module:model/RegisterUserDto} The populated <code>RegisterUserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RegisterUserDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('dateOfBirth'))
        obj.dateOfBirth = ApiClient.convertToType(data['dateOfBirth'], 'Date');
      if (data.hasOwnProperty('accountMode'))
        obj.accountMode = AccountMode.constructFromObject(data['accountMode']);
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
RegisterUserDto.prototype.name = undefined;

/**
 * @member {String} email
 */
RegisterUserDto.prototype.email = undefined;

/**
 * @member {Date} dateOfBirth
 */
RegisterUserDto.prototype.dateOfBirth = undefined;

/**
 * @member {module:model/AccountMode} accountMode
 */
RegisterUserDto.prototype.accountMode = undefined;

/**
 * @member {String} password
 */
RegisterUserDto.prototype.password = undefined;

