/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SetTagsDto model module.
 * @module model/SetTagsDto
 * @version v1
 */
export class SetTagsDto {
  /**
   * Constructs a new <code>SetTagsDto</code>.
   * @alias module:model/SetTagsDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SetTagsDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SetTagsDto} obj Optional instance to populate.
   * @return {module:model/SetTagsDto} The populated <code>SetTagsDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SetTagsDto();
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} tags
 */
SetTagsDto.prototype.tags = undefined;

