/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DetailedTestInfoDto} from './DetailedTestInfoDto';
import {Question} from './Question';

/**
 * The TestFullInfoDto model module.
 * @module model/TestFullInfoDto
 * @version v1
 */
export class TestFullInfoDto {
  /**
   * Constructs a new <code>TestFullInfoDto</code>.
   * @alias module:model/TestFullInfoDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TestFullInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TestFullInfoDto} obj Optional instance to populate.
   * @return {module:model/TestFullInfoDto} The populated <code>TestFullInfoDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TestFullInfoDto();
      if (data.hasOwnProperty('testId'))
        obj.testId = ApiClient.convertToType(data['testId'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('ageRestriction'))
        obj.ageRestriction = ApiClient.convertToType(data['ageRestriction'], 'Number');
      if (data.hasOwnProperty('questionCount'))
        obj.questionCount = ApiClient.convertToType(data['questionCount'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('creationDate'))
        obj.creationDate = ApiClient.convertToType(data['creationDate'], 'Date');
      if (data.hasOwnProperty('questions'))
        obj.questions = ApiClient.convertToType(data['questions'], [Question]);
      if (data.hasOwnProperty('detailedTestInfo'))
        obj.detailedTestInfo = DetailedTestInfoDto.constructFromObject(data['detailedTestInfo']);
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('attemptIds'))
        obj.attemptIds = ApiClient.convertToType(data['attemptIds'], ['Number']);
      if (data.hasOwnProperty('ownerId'))
        obj.ownerId = ApiClient.convertToType(data['ownerId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} testId
 */
TestFullInfoDto.prototype.testId = undefined;

/**
 * @member {String} name
 */
TestFullInfoDto.prototype.name = undefined;

/**
 * @member {Number} ageRestriction
 */
TestFullInfoDto.prototype.ageRestriction = undefined;

/**
 * @member {Number} questionCount
 */
TestFullInfoDto.prototype.questionCount = undefined;

/**
 * @member {String} description
 */
TestFullInfoDto.prototype.description = undefined;

/**
 * @member {Date} creationDate
 */
TestFullInfoDto.prototype.creationDate = undefined;

/**
 * @member {Array.<module:model/Question>} questions
 */
TestFullInfoDto.prototype.questions = undefined;

/**
 * @member {module:model/DetailedTestInfoDto} detailedTestInfo
 */
TestFullInfoDto.prototype.detailedTestInfo = undefined;

/**
 * @member {Array.<String>} tags
 */
TestFullInfoDto.prototype.tags = undefined;

/**
 * @member {Array.<Number>} attemptIds
 */
TestFullInfoDto.prototype.attemptIds = undefined;

/**
 * @member {Number} ownerId
 */
TestFullInfoDto.prototype.ownerId = undefined;

