/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Question} from './Question';

/**
 * The TestDto model module.
 * @module model/TestDto
 * @version v1
 */
export class TestDto {
  /**
   * Constructs a new <code>TestDto</code>.
   * @alias module:model/TestDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TestDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TestDto} obj Optional instance to populate.
   * @return {module:model/TestDto} The populated <code>TestDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TestDto();
      if (data.hasOwnProperty('testId'))
        obj.testId = ApiClient.convertToType(data['testId'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('ageRestriction'))
        obj.ageRestriction = ApiClient.convertToType(data['ageRestriction'], 'Number');
      if (data.hasOwnProperty('questionCount'))
        obj.questionCount = ApiClient.convertToType(data['questionCount'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('creationDate'))
        obj.creationDate = ApiClient.convertToType(data['creationDate'], 'Date');
      if (data.hasOwnProperty('questions'))
        obj.questions = ApiClient.convertToType(data['questions'], [Question]);
    }
    return obj;
  }
}

/**
 * @member {Number} testId
 */
TestDto.prototype.testId = undefined;

/**
 * @member {String} name
 */
TestDto.prototype.name = undefined;

/**
 * @member {Number} ageRestriction
 */
TestDto.prototype.ageRestriction = undefined;

/**
 * @member {Number} questionCount
 */
TestDto.prototype.questionCount = undefined;

/**
 * @member {String} description
 */
TestDto.prototype.description = undefined;

/**
 * @member {Date} creationDate
 */
TestDto.prototype.creationDate = undefined;

/**
 * @member {Array.<module:model/Question>} questions
 */
TestDto.prototype.questions = undefined;

