/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Gender} from './Gender';

/**
 * The UpdateUserDetailedInfoDto model module.
 * @module model/UpdateUserDetailedInfoDto
 * @version v1
 */
export class UpdateUserDetailedInfoDto {
  /**
   * Constructs a new <code>UpdateUserDetailedInfoDto</code>.
   * @alias module:model/UpdateUserDetailedInfoDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UpdateUserDetailedInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateUserDetailedInfoDto} obj Optional instance to populate.
   * @return {module:model/UpdateUserDetailedInfoDto} The populated <code>UpdateUserDetailedInfoDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateUserDetailedInfoDto();
      if (data.hasOwnProperty('gender'))
        obj.gender = Gender.constructFromObject(data['gender']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Gender} gender
 */
UpdateUserDetailedInfoDto.prototype.gender = undefined;

