/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AccountMode} from './AccountMode';
import {DetailedUserInfoDto} from './DetailedUserInfoDto';

/**
 * The UserFullInfoDto model module.
 * @module model/UserFullInfoDto
 * @version v1
 */
export class UserFullInfoDto {
  /**
   * Constructs a new <code>UserFullInfoDto</code>.
   * @alias module:model/UserFullInfoDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserFullInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserFullInfoDto} obj Optional instance to populate.
   * @return {module:model/UserFullInfoDto} The populated <code>UserFullInfoDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserFullInfoDto();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('dateOfBirth'))
        obj.dateOfBirth = ApiClient.convertToType(data['dateOfBirth'], 'Date');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('accountMode'))
        obj.accountMode = AccountMode.constructFromObject(data['accountMode']);
      if (data.hasOwnProperty('detailedUserInfo'))
        obj.detailedUserInfo = DetailedUserInfoDto.constructFromObject(data['detailedUserInfo']);
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('testIds'))
        obj.testIds = ApiClient.convertToType(data['testIds'], ['Number']);
      if (data.hasOwnProperty('attemptIds'))
        obj.attemptIds = ApiClient.convertToType(data['attemptIds'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Number} userId
 */
UserFullInfoDto.prototype.userId = undefined;

/**
 * @member {String} name
 */
UserFullInfoDto.prototype.name = undefined;

/**
 * @member {Date} dateOfBirth
 */
UserFullInfoDto.prototype.dateOfBirth = undefined;

/**
 * @member {String} email
 */
UserFullInfoDto.prototype.email = undefined;

/**
 * @member {module:model/AccountMode} accountMode
 */
UserFullInfoDto.prototype.accountMode = undefined;

/**
 * @member {module:model/DetailedUserInfoDto} detailedUserInfo
 */
UserFullInfoDto.prototype.detailedUserInfo = undefined;

/**
 * @member {Array.<String>} tags
 */
UserFullInfoDto.prototype.tags = undefined;

/**
 * @member {Array.<Number>} testIds
 */
UserFullInfoDto.prototype.testIds = undefined;

/**
 * @member {Array.<Number>} attemptIds
 */
UserFullInfoDto.prototype.attemptIds = undefined;

