/*
 * Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.39
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AccountMode} from './AccountMode';

/**
 * The UserDto model module.
 * @module model/UserDto
 * @version v1
 */
export class UserDto {
  /**
   * Constructs a new <code>UserDto</code>.
   * @alias module:model/UserDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserDto} obj Optional instance to populate.
   * @return {module:model/UserDto} The populated <code>UserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserDto();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('dateOfBirth'))
        obj.dateOfBirth = ApiClient.convertToType(data['dateOfBirth'], 'Date');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('accountMode'))
        obj.accountMode = AccountMode.constructFromObject(data['accountMode']);
    }
    return obj;
  }
}

/**
 * @member {Number} userId
 */
UserDto.prototype.userId = undefined;

/**
 * @member {String} name
 */
UserDto.prototype.name = undefined;

/**
 * @member {Date} dateOfBirth
 */
UserDto.prototype.dateOfBirth = undefined;

/**
 * @member {String} email
 */
UserDto.prototype.email = undefined;

/**
 * @member {module:model/AccountMode} accountMode
 */
UserDto.prototype.accountMode = undefined;

